type: object
properties:
  comment_settings:
    type: string
    description: Comment settings for the entry. `nocomments` disables comments entirely, and `noemail` disables notifications.
    example: nocomments
    enum:
      - nocomments
      - noemail
  age_restriction:
    type: string
    description: Age restriction flag. `none` puts no flags on the entry, `discretion` marks it as "viewer discretion advised", and `restricted` marks it inacessible to users under eighteen.
    example: none
    enum:
      - none
      - discretion
      - restricted
  security:
    type: string
    description: Security level to use. Can be public, private, or a filter name.
    example: public
